export const htmlElements = {
    dateObject: document.querySelector(".date"),
    timeObject: document.querySelector(".current-time"),
    metric: document.querySelector("#metric"),
    imperial: document.querySelector("#imperial"),
    metricLabel: document.querySelector(".metric"),
    imperialLabel: document.querySelector(".imperial"),
    searchBar: document.querySelector(".search-bar"),
    searchBox: document.querySelector(".search-box"),
    magnifyingGlass: document.querySelector(".fa-magnifying-glass"),
    cityElement: document.querySelector(".city-element"),
    currentTemperature: document.querySelector(".current-temperature"),
    currentWeatherType: document.querySelector(".current-weather-type"),
    currentFeelsLike: document.querySelector(".current-feels-like"),
    currentHumidity: document.querySelector(".current-humidity"),
    currentPressure: document.querySelector(".current-pressure"),
    currentWindSpeed: document.querySelector(".current-wind-speed"),
    mainImage: document.querySelector(".main-image"),
    forecastDayElements: document.querySelectorAll(".day"),
    forecastMaxTempElements: document.querySelectorAll(".max-temp"),
    forecastMinTempElements: document.querySelectorAll(".min-temp"),
    forecastIcons: document.querySelectorAll(".forecast-icon"),
    currentLatitude: 40.7831,
    currentLongitude: -73.9712,
}